// src/view/mainPage.tsx
import TripList from '@/component/trip/tripList';

import { globalTrip } from '@/global/trip';
import '@/assets/css/index.css';

function MainPage() {
  return (
    <div id='content'>
      <div id='infoDiv'>서울 촌놈 나들이 기록 📷</div>
      <div id='mapListDiv'>
        {globalTrip.trips.map((trip) => {
          return <TripList trip={trip} key={trip.date}></TripList>;
        })}
      </div>
      <div id='tobecontinueDiv'>서울 촌놈 나들이는 계속 될 예정....🥳</div>
      <div
        className='fixButtonDiv'
        //     :class="{ fix1: !shoesRecom && ayo, fix2: ayo, fixNone: !ayo }"
        id='ayoFilmButtonDiv'
        //   @click="onclickFilm"
      >
        Choi's Film Art~🎞
        <div
          className='fixButtonCloseDiv'
          id='ayoFilmButtonCloseDiv'
          //   @click.stop="onclickClose(1)"
        >
          X
        </div>
      </div>
      <div
        className='fixButtonDiv'
        //:class="{ fix1: shoesRecom, fixNone: !shoesRecom }"
        id='shoesRecomButtonDiv'
        //@click="onclickShoes"
      >
        서울 촌놈의 신발 추천~👟
        <div
          className='fixButtonCloseDiv'
          id='shoesRecomButtonCloseDiv'
          //@click.stop="onclickClose(2)"
        >
          X
        </div>
      </div>
    </div>
  );
}

export default MainPage;

// src/views/mainPage.vue
<template>
  <div id="content">
    <div id="infoDiv">서울 촌놈 나들이 기록 📷</div>
    <div id="mapListDiv">
      <tripList v-for="trip in trips" :key="trip.date" v-bind:trip="trip" />
    </div>
    <div id="shoesRecomButtonDiv" @click="onclickShoes">
      서울 촌놈의 신발 추천~👟
    </div>
  </div>
</template>
  
<script>
import tripList from "@/components/trip/tripList.vue";
import { globalTrip } from "@/global/global.js";

export default {
  name: "mainPage",
  methods: {
    onClickMap(date) {
      this.$router.push("/map" + date);
    },
    onclickShoes() {
      this.$router.push("shoesRecom");
    },
  },
  data() {
    return {
      trips: globalTrip.trips,
    };
  },
  components: {
    tripList,
  },
};
</script>
  
  <!-- Add "scoped" attribute to limit CSS to this component only -->
<style>
@import "../assets/css/index.css";
</style>
