// src/components/shoe/brandList.vue
<template>
  <div class="brandListDiv" v-bind:id="brand.divId">
    <img class="brandListImg" :src="this.brand.img" />
    <div class="brandListInfo">
      <div class="brandListName">{{ brand.name }}</div>
      <div class="brandListDesc">{{ brand.desc }}</div>
    </div>
  </div>
  <div class="shoesListDiv">
    <shoesList
      v-for="shoe in brand.shoes"
      :key="shoe.id"
      v-bind:shoe="shoe"
    ></shoesList>
  </div>
</template>
  
<script>
import shoesList from "./shoesList.vue";

export default {
  name: "brandList",
  props: { brand: Object },
  methods: {},
  data() {
    return {};
  },
  components: {
    shoesList,
  },
};
</script>
  
<style>
@import "@/assets/css/shoesRecom.css";
</style>

// src/component/shoes/brandList.tsx
import { useNavigate } from 'react-router';
import type { Brand } from '@/global/shoes';
import ShoesList from './shoesList';

interface BrandListProps {
  brand: Brand;
}

function BrandList({ brand }: BrandListProps) {
  const navigate = useNavigate();

  const onClickShoesList = (shoesId: string) => {
    navigate(`/${brand.brandId}/${shoesId}`);
  };

  return (
    <>
      <div className='brandListDiv' id={brand.divId}>
        <img className='brandListImg' src={brand.img} alt='' />
        <div className='brandListInfo'>
          <div className='brandListName'>{brand.name}</div>
          <div className='brandListDesc'>{brand.desc}</div>
        </div>
      </div>
      <div className='shoesListDiv'>
        {brand.shoes.map((shoe) => {
          return (
            <ShoesList
              key={shoe.id}
              shoe={shoe}
              onClickShoesList={onClickShoesList}
            ></ShoesList>
          );
        })}
      </div>
    </>
  );
}

export default BrandList;
