// src/components/shoe/shoesList.vue
<template>
  <div class="shoesDiv" v-bind:id="shoe.divId">
    <div class="shoesImgDiv">
      <img class="shoesImg" :src="shoe.img" />
    </div>
    <div class="shoes">{{ shoe.name }}</div>
    <div class="price">{{ shoe.price }}</div>
  </div>
</template>
    
<script>
export default {
  name: "shoesList",
  props: { shoe: Object },
  methods: {},
  data() {
    return {};
  },
};
</script>
    
<style>
@import "@/assets/css/shoesRecom.css";
</style>

// src/component/shoes/shoesList.tsx
import type { Shoe } from '@/global/shoes';

interface ShoesListProps {
  shoe: Shoe;
  onClickShoesList: (shoesId: string) => void;
}

function ShoesList(shoesListProps: ShoesListProps) {
  const { shoe, onClickShoesList } = shoesListProps;

  return (
    <div
      className='shoesDiv'
      id={shoe.divId}
      onClick={() => onClickShoesList(shoe.shoesId)}
    >
      <div className='shoesImgDiv'>
        <img className='shoesImg' src={shoe.img} alt='' />
      </div>
      <div className='shoes'>{shoe.name}</div>
      <div className='price'>{shoe.price}</div>
    </div>
  );
}

export default ShoesList;
