// src/App.tsx
import slcnImg from '@/assets/img/SLCN.png';
import MainPage from '@/view/mainPage';
import TripPage from '@/view/tripPage';
import '@/assets/css/common.css';
import { Route, Routes, useNavigate } from 'react-router';

function App() {
  const navigate = useNavigate();

  const onClickSlcn = () => {
    navigate('/');
  };

  return (
    <div id='mainDiv'>
      <div id='header'>
        <img id='SLCN' src={slcnImg} alt='' onClick={onClickSlcn} />
      </div>
      <Routes>
        <Route path='/' element={<MainPage></MainPage>}></Route>
        <Route path='/map/:date' element={<TripPage></TripPage>}></Route>
      </Routes>
      <div id='footer'>© Seoul CHONNOM</div>
    </div>
  );
}

export default App;

// src/App.vue
<template>
  <div id="mainDiv">
    <div id="header">
      <img id="SLCN" src="./assets/img/SLCN.png" />
    </div>
    <router-view></router-view>
    <div id="footer">© Seoul CHONNOM</div>
  </div>
</template>

<script>
export default {
  name: "App",
  components: {},
};
</script>

<style>
@import "./assets/css/common.css";
#app {
  background-color: rgb(241, 214, 208);
}
</style>
